//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace SilverLegend.AnalyticsSvcRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="AnalyticsSvcRef.AnalyticsSvc")]
    public interface AnalyticsSvc {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:AnalyticsSvc/Yo", ReplyAction="urn:AnalyticsSvc/YoResponse")]
        System.IAsyncResult BeginYo(int gameId, string notification, string parameters, System.AsyncCallback callback, object asyncState);
        
        void EndYo(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AnalyticsSvcChannel : SilverLegend.AnalyticsSvcRef.AnalyticsSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnalyticsSvcClient : System.ServiceModel.ClientBase<SilverLegend.AnalyticsSvcRef.AnalyticsSvc>, SilverLegend.AnalyticsSvcRef.AnalyticsSvc {
        
        private BeginOperationDelegate onBeginYoDelegate;
        
        private EndOperationDelegate onEndYoDelegate;
        
        private System.Threading.SendOrPostCallback onYoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public AnalyticsSvcClient() {
        }
        
        public AnalyticsSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnalyticsSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalyticsSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalyticsSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> YoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverLegend.AnalyticsSvcRef.AnalyticsSvc.BeginYo(int gameId, string notification, string parameters, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginYo(gameId, notification, parameters, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SilverLegend.AnalyticsSvcRef.AnalyticsSvc.EndYo(System.IAsyncResult result) {
            base.Channel.EndYo(result);
        }
        
        private System.IAsyncResult OnBeginYo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int gameId = ((int)(inValues[0]));
            string notification = ((string)(inValues[1]));
            string parameters = ((string)(inValues[2]));
            return ((SilverLegend.AnalyticsSvcRef.AnalyticsSvc)(this)).BeginYo(gameId, notification, parameters, callback, asyncState);
        }
        
        private object[] OnEndYo(System.IAsyncResult result) {
            ((SilverLegend.AnalyticsSvcRef.AnalyticsSvc)(this)).EndYo(result);
            return null;
        }
        
        private void OnYoCompleted(object state) {
            if ((this.YoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.YoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void YoAsync(int gameId, string notification, string parameters) {
            this.YoAsync(gameId, notification, parameters, null);
        }
        
        public void YoAsync(int gameId, string notification, string parameters, object userState) {
            if ((this.onBeginYoDelegate == null)) {
                this.onBeginYoDelegate = new BeginOperationDelegate(this.OnBeginYo);
            }
            if ((this.onEndYoDelegate == null)) {
                this.onEndYoDelegate = new EndOperationDelegate(this.OnEndYo);
            }
            if ((this.onYoCompletedDelegate == null)) {
                this.onYoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnYoCompleted);
            }
            base.InvokeAsync(this.onBeginYoDelegate, new object[] {
                        gameId,
                        notification,
                        parameters}, this.onEndYoDelegate, this.onYoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverLegend.AnalyticsSvcRef.AnalyticsSvc CreateChannel() {
            return new AnalyticsSvcClientChannel(this);
        }
        
        private class AnalyticsSvcClientChannel : ChannelBase<SilverLegend.AnalyticsSvcRef.AnalyticsSvc>, SilverLegend.AnalyticsSvcRef.AnalyticsSvc {
            
            public AnalyticsSvcClientChannel(System.ServiceModel.ClientBase<SilverLegend.AnalyticsSvcRef.AnalyticsSvc> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginYo(int gameId, string notification, string parameters, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = gameId;
                _args[1] = notification;
                _args[2] = parameters;
                System.IAsyncResult _result = base.BeginInvoke("Yo", _args, callback, asyncState);
                return _result;
            }
            
            public void EndYo(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Yo", _args, result);
            }
        }
    }
}
