using System;
using System.Collections.Generic;
using System.Text;

public enum GameBitmapEnumeration
{

    ////////////////////////////////////////////////////////////////
    // *************************************************************
    // LOAD DIRECTORY
    bmpSPLASHSCREEN,
    bmpINVISIBLE,
    bmpBTNTOGGLE,
    bmpWHITE_DOT,
    // CharSet
    bmpALP_COLON,
    bmpALP_PERIOD,
    bmpDIG_0,
    bmpDIG_1,
    bmpDIG_2,
    bmpDIG_3,
    bmpDIG_4,
    bmpDIG_5,
    bmpDIG_6,
    bmpDIG_7,
    bmpDIG_8,
    bmpDIG_9,
    // Cursors
    bmpMOU_SELECT1,
    bmpMOU_SELECT2,
    bmpMOU_SELECT3,
    bmpMOU_TARBL,
    bmpMOU_TARBR,
    bmpMOU_TARTL,
    bmpMOU_TARTR,

    ////////////////////////////////////////////////////////////////
    // *************************************************************
    // GAME DIRECTORY
    // Frosh Sprites (and lots of 'em)
    bmpFR1_1,
    bmpFR1_2,
    bmpFR1_3,
    bmpFR1_4,
    bmpFR1_5,
    bmpFR1_6,
    bmpFR2_1,
    bmpFR2_2,
    bmpFR3_1,
    bmpFR3_2,
    bmpFR4A_1,
    bmpFR4A_2,
    bmpFR4A_3,
    bmpFR4A_4,
    bmpFR4B_1,
    bmpFR4B_2,
    bmpFR5A_1,
    bmpFR5A_2,
    bmpFR5A_3,
    bmpFR5A_4,
    bmpFR5B_1,
    bmpFR5B_2,
    bmpFR5B_3,
    bmpFR5B_4,
    bmpFR5B_5,
    bmpFR5B_6,
    bmpFR5C_1,
    bmpFR5C_2,
    bmpFR5D_1,
    bmpFR5D_2,
    bmpFR5D_3,
    bmpFR6A_1,
    bmpFR6A_2,
    bmpFR6B_1,
    bmpFR6B_2,
    bmpFR6C_1,
    bmpFR6C_2,
    bmpFR6D_1,
    bmpFR6D_2,
    bmpFR6D_3,
    bmpFR6D_4,
    bmpFR6E_1,
    bmpFR6E_2,
    bmpFR6F_1,
    bmpFR6F_2,
    bmpFR6F_3,

    bmpFR7A_1,
    bmpFR7A_2,
    bmpFR7A_3,
    bmpFR7B_1,
    bmpFR7B_2,
    bmpFR8_1,
    bmpFR8_2,
    bmpFR9A_1,
    bmpFR9A_2,
    bmpFR9A_3,
    bmpFR9B_1,
    bmpFR9B_2,
    bmpFR9B_3,
    bmpFR10_1,
    bmpFR10_2,
    bmpFR10_3,
    bmpFR11_1,
    bmpFR11_2,
    bmpFR11_3,
    bmpFR11_4,
    bmpFR11_5,
    bmpFR11_6,
    bmpFR11_7,
    bmpFR11_8,
    bmpFR11_9,
    bmpFR11_10,
    bmpFR11B_1,
    bmpFR11B_2,
    bmpFR11B_3,
    bmpFR14_1,
    bmpFR14_2,
    bmpFR14_3,
    bmpFR14_4,
    bmpFR15_1,
    bmpFR15_2,
    bmpFR15_3,
    bmpFR16A_1,
    bmpFR16B_1,
    bmpFR16B_2,
    bmpFR16B_3,
    bmpFR16C_1,
    bmpFR16C_2,
    bmpFR16D_1,
    bmpFR16D_2,
    bmpFR16D_3,
    bmpFR16D_4,
    bmpFR16E_1,
    bmpFR16E_2,
    bmpFR16F_1,
    bmpFR16F_2,
    bmpPOOF1,
    bmpPOOF2,
    bmpPOOF3,
    bmpPOOF4,

    // Foreground-to-pit
    // Weapon Offerings
    bmpOFFERAPPLES,
    bmpOFFERPIZZA,
    bmpOFFERCLARK,
    bmpOFFEREXAM,
    bmpOFFERHOSE,

    // Arm / Hand
    bmpHAND0_1,
    bmpHAND0_2,
    bmpHAND0_3,
    bmpHAND1_1,
    bmpHAND1_2,
    bmpHAND1_3,
    bmpHAND1_4,
    bmpHAND1_5,
    bmpHAND1_6,
    bmpHAND1_7,
    bmpHAND1_8,
    bmpHAND2_1,
    bmpHAND2_2,
    bmpHAND3_1,
    bmpHAND3_2,
    bmpHAND3_3,
    bmpHAND3_4,
    bmpHAND3_5,
    bmpHAND4_1,
    bmpHAND4_2,
    bmpHAND4_3,
    bmpHAND5_1,
    bmpHAND5_2,
    bmpHAND5_3,
    bmpHAND7_1,
    bmpHAND7_2,
    bmpHAND7_3,
    bmpHAND7_4,
    bmpHAND7_5,
    bmpHAND7_6,
    bmpHAND7_7,
    bmpHAND9_1,
    bmpCLOSEUPBEER1,
    bmpCLOSEUPBEER2,

    // Apple
    bmpAPPLE1_1,
    bmpAPPLE2_1,
    bmpAPPLE3_1,
    bmpAPPLE4_1,
    bmpAPPLE5_1,
    bmpAPPLE5_2,
    bmpAPPLE5_3,
    bmpAPPLE5_4,
    bmpAPPLE6_1,
    bmpAPPLE7_1,
    bmpWHAP_1,
    bmpGLINT_1,
    bmpGLINT_2,
    // Pizza
    bmpPIZZA1_1,
    bmpPIZZA2_1,
    bmpPIZZA3_1,
    bmpPIZZA4_1,
    bmpPIZZA4_2,
    bmpPIZZA4_3,
    bmpPIZZA4_4,
    bmpPIZZA4_5,
    bmpPIZZA4_6,
    bmpPIZZA4_7,
    bmpPIZZA4_8,
    bmpPIZZA5_1,
    bmpPIZZA6_1,
    bmpPIZZA7_1,
    // Clark Mug
    bmpCLARK1_1,
    bmpCLARK2_1,
    bmpCLARK3_1,
    bmpCLARK4_1,
    bmpCLARK5A_1,
    bmpCLARK5A_2,
    bmpCLARK5A_3,
    bmpCLARK5A_4,
    bmpCLARK5B_1,
    bmpCLARK6_1,
    bmpCLARK7_1,
    // 114 Exam
    bmpEXAM1_1,
    bmpEXAM2_1,
    bmpEXAM3_1,
    bmpEXAM4_1,
    bmpEXAM4_2,
    bmpEXAM4_3,
    bmpEXAM4_4,
    // HOSE!
    bmpHOSEBALL1,
    bmpHOSEBALL2,
    bmpHOSEBALL3,
    bmpHOSEBALL4,
    bmpHOSEBALL5,
    bmpHOSEBALL6,
    bmpHOSEBALL7,
    bmpHSPLASH1_1,
    bmpHSPLASH1_2,
    bmpHSPLASH1_3,
    bmpHSPLASH1_4,
    bmpHSPLASH1_5,
    bmpHSPLASH2_1,
    bmpHSPLASH2_2,
    bmpHSPLASH2_3,
    bmpHSPLASH2_4,
    bmpHSPLASH2_5,
    bmpHSPLASH3_1,
    bmpHSPLASH3_2,
    bmpHSPLASH3_3,
    bmpHSPLASH3_4,
    bmpHSPLASH3_5,
    bmpSPRAY1,
    bmpSPRAY2,

    // In-the-pit elements
    // Pole
    bmpPOLE,
    bmpTAM0_1,
    bmpTAM0_2,
    bmpTAM1_1,
    bmpTAM1_2,
    bmpTAM2_1,
    bmpTAM2_2,
    // Water
    bmpWATER,
    bmpSPLASHS1,
    bmpSPLASHS2,
    bmpSPLASHS3,
    bmpSPLASHM1,
    bmpSPLASHM2,
    bmpSPLASHM3,
    bmpSPLASHL1,
    bmpSPLASHL2,
    bmpSPLASHL3,
    bmpRIPPLE1,
    bmpRIPPLE2,
    bmpRIPPLE3,
    bmpWAKE1,
    bmpWAKE2,
    bmpWAKE3,
    // Artsci student
    // FEMALE
    bmpARTSCIF_FALL1,
    bmpARTSCIF_FALL2,
    bmpARTSCIF_FALL3,
    bmpARTSCIF_HIT1,
    bmpARTSCIF_POPUP1,
    bmpARTSCIF_POPUP2,
    bmpARTSCIF_WADE1,
    bmpARTSCIF_WADE2,
    bmpARTSCIF_WADE3,
    bmpARTSCIF_WADE4,
    // MALE
    bmpARTSCIM_FALL1,
    bmpARTSCIM_FALL2,
    bmpARTSCIM_FALL3,
    bmpARTSCIM_HIT1,
    bmpARTSCIM_HIT2,
    bmpARTSCIM_POPUP1,
    bmpARTSCIM_POPUP2,
    bmpARTSCIM_POPUP3,
    bmpARTSCIM_POPUP4,
    bmpARTSCIM_POPUP5,
    bmpARTSCIM_WADE1,
    bmpARTSCIM_WADE2,
    bmpARTSCIM_WADE3,
    bmpARTSCIM_WADE4,
    // Commerce Student
    // FEMALE
    bmpCOMMIEF_FALL1,
    bmpCOMMIEF_FALL2,
    bmpCOMMIEF_FALL3,
    bmpCOMMIEF_HIT1,
    bmpCOMMIEF_HIT2,
    bmpCOMMIEF_POPUP1,
    bmpCOMMIEF_POPUP2,
    bmpCOMMIEF_POPUP3,
    bmpCOMMIEF_POPUP4,
    bmpCOMMIEF_POPUP5,
    bmpCOMMIEF_WADE1,
    bmpCOMMIEF_WADE2,
    bmpCOMMIEF_WADE3,
    bmpCOMMIEF_WADE4,
    // MALE
    bmpCOMMIEM_FALL1,
    bmpCOMMIEM_FALL2,
    bmpCOMMIEM_FALL3,
    bmpCOMMIEM_HIT1,
    bmpCOMMIEM_POPUP1,
    bmpCOMMIEM_POPUP2,
    bmpCOMMIEM_POPUP3,
    bmpCOMMIEM_POPUP4,
    bmpCOMMIEM_POPUP5,
    bmpCOMMIEM_WADE1,
    bmpCOMMIEM_WADE2,
    bmpCOMMIEM_WADE3,
    // Upper Year Student (Al)
    bmpPOPBOY1_1,
    bmpPOPBOY1_2,
    bmpPOPBOY1_3,
    bmpPOPBOY2_1,
    bmpPOPBOY2_2,
    bmpPOPBOY2_3,
    bmpPOPBOY2_4,
    bmpPOPBOY3_1,
    bmpPOPBOY3_2,
    bmpPOPBOY3_3,
    bmpPOPBOY3_4,
    bmpPOPBOY4_1,
    bmpPOPBOY4_2,
    bmpPOPBOY5_1,
    bmpPOPBOY5_2,
    bmpPOPBOY6_1,
    bmpPOPBOY6_2,
    bmpPOPBOY7_1,
    bmpPOPBOY7_2,
    bmpPOPBOY7_3,
    bmpPOPBOY7_4,

    // Background elements
    // Podium
    bmpPODIUM,
    // PRESIDENT
    bmpPREZ1_1,
    bmpPREZ1_2,
    bmpPREZ1_3,
    bmpPREZ2_1,
    bmpPREZ2_2,
    bmpPREZ2_3,
    bmpPREZ3_1,
    bmpPREZ3_2,
    bmpPREZ4_1,
    bmpPREZ4_2,
    // Frecs
    bmpAF_AppleBlock,
    bmpAF_Boo1,
    bmpAF_Boo2,
    bmpAF_Boo3,
    bmpAF_JacketSlam1,
    bmpAF_JacketSlam2,
    bmpAF_JacketSlam3,
    bmpAF_LameFrosh1,
    bmpAF_LameFrosh2,
    bmpAF_LameFrosh3,
    bmpAF_LookULR1,
    bmpAF_LookULR2,
    bmpAF_LookULR3,
    bmpAF_LookUp1,
    bmpAF_Milling1,
    bmpAF_Milling2,
    bmpAF_Part1,
    bmpAF_Part2,
    bmpAF_Shout1,
    bmpAF_Shout2,
    bmpAF_Shout3,
    bmpAF_Slam1,
    bmpAF_Slam2,
    bmpAF_Slam3,
    bmpAF_StayinAlive1,
    bmpAF_StayinAlive2,
    bmpAF_Wave1,
    bmpAF_Wave2,
    bmpAF_Wave3,
    bmpGF_AppleBlock,
    bmpGF_Boo1,
    bmpGF_Boo2,
    bmpGF_Boo3,
    bmpGF_Cheer1,
    bmpGF_Cheer2,
    bmpGF_Cheer3,
    bmpGF_Cheer4,
    bmpGF_LookULR1,
    bmpGF_LookULR2,
    bmpGF_LookULR3,
    bmpGF_LookUp1,
    bmpGF_Milling1,
    bmpGF_Milling2,
    bmpGF_Milling3,
    bmpGF_Shout1,
    bmpGF_Shout2,
    bmpGF_Slam1,
    bmpGF_Slam2,
    bmpGF_Slam3,
    bmpGF_StayinAlive1,
    bmpGF_StayinAlive2,
    bmpGF_Wave1,
    bmpGF_Wave2,
    bmpGF_Wave3,

    // Male SciCon (Brian)
    bmpSCICONM1,
    bmpSCICONM2,
    bmpSCICONM3,
    // Female SciCon (Marie-Claire)
    bmpSCICONF1,
    bmpSCICONF2,

    // Misc. Background
    bmpTREES,
    bmpBACKDROP,
    // Sky elements
    bmpCLOUDS,
    bmpGWBALLOONL,
    bmpGWBALLOONLBANG,
    bmpGWBALLOONR,
    bmpGWBALLOONRBANG,
    bmpHIPPO0_1,
    bmpHIPPO0_2,
    bmpHIPPO1_1,
    bmpHIPPO1_2,
    bmpHIPPO1_3,
    bmpHIPPO2_1,
    bmpHIPPO2_2,
    bmpHIPPO2_3,
    bmpHIPPO3_1,
    bmpHIPPO3_2,
    bmpHIPPO3_3,
    bmpHIPPO4_1,
    bmpHIPPO4_2,
    bmpHIPPOWORDS1,
    bmpHIPPOWORDS2,
    bmpHIPPOWORDS3,
    bmpHIPPOWORDS4,
    bmpHIPPOWORDS5,
    bmpHIPPOWORDS6,
    // Icons of Weapons
    bmpICOBAR,
    bmpICOAPPLE1,
    bmpICOAPPLE2,
    bmpICOAPPLE3,
    bmpICOPIZZA1,
    bmpICOPIZZA2,
    bmpICOPIZZA3,
    bmpICOCLARK1,
    bmpICOCLARK2,
    bmpICOCLARK3,
    bmpICOEXAM1,
    bmpICOEXAM2,
    bmpICOEXAM3,
    bmpFORGE1_1,
    bmpFORGE1_2,
    bmpFORGE1_3,
    bmpFORGE1_4,
    bmpFORGE2_2,
    bmpFORGE2_3,
    bmpFORGE2_4,
    bmpFORGE2_5,
    bmpFORGE3_2,
    bmpFORGE3_3,
    bmpFORGE3_4,
    bmpFORGE3_5,
    bmpFORGE4_2,
    bmpFORGE4_3,
    bmpFORGE4_4,
    bmpFORGE4_5,
    bmpFORGEDOWN,
    bmpICORING1,
    bmpICORING2,
    bmpICORING3,
    bmpICORING4,
    bmpICORING5,
    bmpPOWERBAR,
    bmpRINGBAR,
    bmpWATERBAR,
    bmpCONSOLE,
    bmpGRID1,
    bmpGRID2,
    bmpGRID3,
    bmpTRI,
    bmpPUB,
    bmpBAN,

    ////////////////////////////////////////////////////////////////
    // *************************************************************
    // MENU DIRECTORY
    // Startup Screens
    bmpJACKETBACK,

    // Options
    bmpOPTIONSBACK,

    // Title
    bmpTITLEBACK,
    bmpTITLESTARTGLOW1,
    bmpTITLESTART,
    bmpTITLESTARTGLOW2,
    bmpTITLESTARTGLOW3,
    bmpTITLEOPTIONS,
    bmpTITLEOPTIONSGLOW1,
    bmpTITLEOPTIONSGLOW2,
    bmpTITLEOPTIONSGLOW3,
    bmpTITLEEXIT,
    bmpTITLECREDITS1,
    bmpTITLECREDITS2,
    bmpTITLECREDITS3,
    bmpTITLECREDITS4,
    bmpTITLECREDITS5,
    bmpTITLECREDITS6,
    bmpTITLECREDITS7,

    // Achievement unlocked (loaded here to use anywhere
    bmpACHIEVEMENTUNLOCKED,
    bmpACHIEVEMENTUNLOCKED2,

    // Discipline (Jacket)
    bmpMENUJACKET,
    bmpBAR1,
    bmpBAR2,
    bmpBAR3,
    bmpBAR4,
    bmpBAR5,
    bmpBAR6,
    bmpBAR7,
    bmpBAR8,
    bmpBAR9,
    bmpBAR10,
    bmpBAR11,
    bmpBAR12,
    bmpBAR13,
    bmpBAR14,
    bmpBAR15,
    bmpBAR16,
    bmpBAR17,
    bmpBAR18,
    bmpBAR19,
    bmpBAR20,
    bmpMENUPREVBARSCREEN,
    bmpBTNRETURN,
    bmpTXTSELECT,
    bmpMENUPASSCREST1,
    bmpMENUPASSCREST2,
    bmpMENUPASSCREST3,


    ////////////////////////////////////////////////////////////////
    // *************************************************************
    // TRANSITION DIRECTORY
    bmpSLAMJACKET1,
    bmpSLAMJACKET2,
    bmpSLAMJACKET3,
    bmpSLAMJACKET4,


    bmpENDOFBITMAPS
}

