//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace SilverLegend.LeaderboardSvcRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="LeaderboardSvcRef.LeaderboardSvc")]
    public interface LeaderboardSvc {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:LeaderboardSvc/UpdateLeaderboard", ReplyAction="urn:LeaderboardSvc/UpdateLeaderboardResponse")]
        System.IAsyncResult BeginUpdateLeaderboard(int longestGame, int achievementTotal, System.AsyncCallback callback, object asyncState);
        
        void EndUpdateLeaderboard(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:LeaderboardSvc/GetLongestGame", ReplyAction="urn:LeaderboardSvc/GetLongestGameResponse")]
        System.IAsyncResult BeginGetLongestGame(System.AsyncCallback callback, object asyncState);
        
        int EndGetLongestGame(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:LeaderboardSvc/GetHighestAchievementTotal", ReplyAction="urn:LeaderboardSvc/GetHighestAchievementTotalResponse")]
        System.IAsyncResult BeginGetHighestAchievementTotal(System.AsyncCallback callback, object asyncState);
        
        int EndGetHighestAchievementTotal(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:LeaderboardSvc/GetTopTenLongestGames", ReplyAction="urn:LeaderboardSvc/GetTopTenLongestGamesResponse")]
        System.IAsyncResult BeginGetTopTenLongestGames(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<int> EndGetTopTenLongestGames(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LeaderboardSvcChannel : SilverLegend.LeaderboardSvcRef.LeaderboardSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLongestGameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLongestGameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHighestAchievementTotalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetHighestAchievementTotalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTopTenLongestGamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTopTenLongestGamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<int> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<int>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeaderboardSvcClient : System.ServiceModel.ClientBase<SilverLegend.LeaderboardSvcRef.LeaderboardSvc>, SilverLegend.LeaderboardSvcRef.LeaderboardSvc {
        
        private BeginOperationDelegate onBeginUpdateLeaderboardDelegate;
        
        private EndOperationDelegate onEndUpdateLeaderboardDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateLeaderboardCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLongestGameDelegate;
        
        private EndOperationDelegate onEndGetLongestGameDelegate;
        
        private System.Threading.SendOrPostCallback onGetLongestGameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetHighestAchievementTotalDelegate;
        
        private EndOperationDelegate onEndGetHighestAchievementTotalDelegate;
        
        private System.Threading.SendOrPostCallback onGetHighestAchievementTotalCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTopTenLongestGamesDelegate;
        
        private EndOperationDelegate onEndGetTopTenLongestGamesDelegate;
        
        private System.Threading.SendOrPostCallback onGetTopTenLongestGamesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LeaderboardSvcClient() {
        }
        
        public LeaderboardSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeaderboardSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeaderboardSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeaderboardSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdateLeaderboardCompleted;
        
        public event System.EventHandler<GetLongestGameCompletedEventArgs> GetLongestGameCompleted;
        
        public event System.EventHandler<GetHighestAchievementTotalCompletedEventArgs> GetHighestAchievementTotalCompleted;
        
        public event System.EventHandler<GetTopTenLongestGamesCompletedEventArgs> GetTopTenLongestGamesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverLegend.LeaderboardSvcRef.LeaderboardSvc.BeginUpdateLeaderboard(int longestGame, int achievementTotal, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateLeaderboard(longestGame, achievementTotal, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SilverLegend.LeaderboardSvcRef.LeaderboardSvc.EndUpdateLeaderboard(System.IAsyncResult result) {
            base.Channel.EndUpdateLeaderboard(result);
        }
        
        private System.IAsyncResult OnBeginUpdateLeaderboard(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int longestGame = ((int)(inValues[0]));
            int achievementTotal = ((int)(inValues[1]));
            return ((SilverLegend.LeaderboardSvcRef.LeaderboardSvc)(this)).BeginUpdateLeaderboard(longestGame, achievementTotal, callback, asyncState);
        }
        
        private object[] OnEndUpdateLeaderboard(System.IAsyncResult result) {
            ((SilverLegend.LeaderboardSvcRef.LeaderboardSvc)(this)).EndUpdateLeaderboard(result);
            return null;
        }
        
        private void OnUpdateLeaderboardCompleted(object state) {
            if ((this.UpdateLeaderboardCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateLeaderboardCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateLeaderboardAsync(int longestGame, int achievementTotal) {
            this.UpdateLeaderboardAsync(longestGame, achievementTotal, null);
        }
        
        public void UpdateLeaderboardAsync(int longestGame, int achievementTotal, object userState) {
            if ((this.onBeginUpdateLeaderboardDelegate == null)) {
                this.onBeginUpdateLeaderboardDelegate = new BeginOperationDelegate(this.OnBeginUpdateLeaderboard);
            }
            if ((this.onEndUpdateLeaderboardDelegate == null)) {
                this.onEndUpdateLeaderboardDelegate = new EndOperationDelegate(this.OnEndUpdateLeaderboard);
            }
            if ((this.onUpdateLeaderboardCompletedDelegate == null)) {
                this.onUpdateLeaderboardCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateLeaderboardCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateLeaderboardDelegate, new object[] {
                        longestGame,
                        achievementTotal}, this.onEndUpdateLeaderboardDelegate, this.onUpdateLeaderboardCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverLegend.LeaderboardSvcRef.LeaderboardSvc.BeginGetLongestGame(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLongestGame(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int SilverLegend.LeaderboardSvcRef.LeaderboardSvc.EndGetLongestGame(System.IAsyncResult result) {
            return base.Channel.EndGetLongestGame(result);
        }
        
        private System.IAsyncResult OnBeginGetLongestGame(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverLegend.LeaderboardSvcRef.LeaderboardSvc)(this)).BeginGetLongestGame(callback, asyncState);
        }
        
        private object[] OnEndGetLongestGame(System.IAsyncResult result) {
            int retVal = ((SilverLegend.LeaderboardSvcRef.LeaderboardSvc)(this)).EndGetLongestGame(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLongestGameCompleted(object state) {
            if ((this.GetLongestGameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLongestGameCompleted(this, new GetLongestGameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLongestGameAsync() {
            this.GetLongestGameAsync(null);
        }
        
        public void GetLongestGameAsync(object userState) {
            if ((this.onBeginGetLongestGameDelegate == null)) {
                this.onBeginGetLongestGameDelegate = new BeginOperationDelegate(this.OnBeginGetLongestGame);
            }
            if ((this.onEndGetLongestGameDelegate == null)) {
                this.onEndGetLongestGameDelegate = new EndOperationDelegate(this.OnEndGetLongestGame);
            }
            if ((this.onGetLongestGameCompletedDelegate == null)) {
                this.onGetLongestGameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLongestGameCompleted);
            }
            base.InvokeAsync(this.onBeginGetLongestGameDelegate, null, this.onEndGetLongestGameDelegate, this.onGetLongestGameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverLegend.LeaderboardSvcRef.LeaderboardSvc.BeginGetHighestAchievementTotal(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetHighestAchievementTotal(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int SilverLegend.LeaderboardSvcRef.LeaderboardSvc.EndGetHighestAchievementTotal(System.IAsyncResult result) {
            return base.Channel.EndGetHighestAchievementTotal(result);
        }
        
        private System.IAsyncResult OnBeginGetHighestAchievementTotal(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverLegend.LeaderboardSvcRef.LeaderboardSvc)(this)).BeginGetHighestAchievementTotal(callback, asyncState);
        }
        
        private object[] OnEndGetHighestAchievementTotal(System.IAsyncResult result) {
            int retVal = ((SilverLegend.LeaderboardSvcRef.LeaderboardSvc)(this)).EndGetHighestAchievementTotal(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetHighestAchievementTotalCompleted(object state) {
            if ((this.GetHighestAchievementTotalCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetHighestAchievementTotalCompleted(this, new GetHighestAchievementTotalCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetHighestAchievementTotalAsync() {
            this.GetHighestAchievementTotalAsync(null);
        }
        
        public void GetHighestAchievementTotalAsync(object userState) {
            if ((this.onBeginGetHighestAchievementTotalDelegate == null)) {
                this.onBeginGetHighestAchievementTotalDelegate = new BeginOperationDelegate(this.OnBeginGetHighestAchievementTotal);
            }
            if ((this.onEndGetHighestAchievementTotalDelegate == null)) {
                this.onEndGetHighestAchievementTotalDelegate = new EndOperationDelegate(this.OnEndGetHighestAchievementTotal);
            }
            if ((this.onGetHighestAchievementTotalCompletedDelegate == null)) {
                this.onGetHighestAchievementTotalCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHighestAchievementTotalCompleted);
            }
            base.InvokeAsync(this.onBeginGetHighestAchievementTotalDelegate, null, this.onEndGetHighestAchievementTotalDelegate, this.onGetHighestAchievementTotalCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverLegend.LeaderboardSvcRef.LeaderboardSvc.BeginGetTopTenLongestGames(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTopTenLongestGames(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<int> SilverLegend.LeaderboardSvcRef.LeaderboardSvc.EndGetTopTenLongestGames(System.IAsyncResult result) {
            return base.Channel.EndGetTopTenLongestGames(result);
        }
        
        private System.IAsyncResult OnBeginGetTopTenLongestGames(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverLegend.LeaderboardSvcRef.LeaderboardSvc)(this)).BeginGetTopTenLongestGames(callback, asyncState);
        }
        
        private object[] OnEndGetTopTenLongestGames(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<int> retVal = ((SilverLegend.LeaderboardSvcRef.LeaderboardSvc)(this)).EndGetTopTenLongestGames(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTopTenLongestGamesCompleted(object state) {
            if ((this.GetTopTenLongestGamesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTopTenLongestGamesCompleted(this, new GetTopTenLongestGamesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTopTenLongestGamesAsync() {
            this.GetTopTenLongestGamesAsync(null);
        }
        
        public void GetTopTenLongestGamesAsync(object userState) {
            if ((this.onBeginGetTopTenLongestGamesDelegate == null)) {
                this.onBeginGetTopTenLongestGamesDelegate = new BeginOperationDelegate(this.OnBeginGetTopTenLongestGames);
            }
            if ((this.onEndGetTopTenLongestGamesDelegate == null)) {
                this.onEndGetTopTenLongestGamesDelegate = new EndOperationDelegate(this.OnEndGetTopTenLongestGames);
            }
            if ((this.onGetTopTenLongestGamesCompletedDelegate == null)) {
                this.onGetTopTenLongestGamesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTopTenLongestGamesCompleted);
            }
            base.InvokeAsync(this.onBeginGetTopTenLongestGamesDelegate, null, this.onEndGetTopTenLongestGamesDelegate, this.onGetTopTenLongestGamesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverLegend.LeaderboardSvcRef.LeaderboardSvc CreateChannel() {
            return new LeaderboardSvcClientChannel(this);
        }
        
        private class LeaderboardSvcClientChannel : ChannelBase<SilverLegend.LeaderboardSvcRef.LeaderboardSvc>, SilverLegend.LeaderboardSvcRef.LeaderboardSvc {
            
            public LeaderboardSvcClientChannel(System.ServiceModel.ClientBase<SilverLegend.LeaderboardSvcRef.LeaderboardSvc> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginUpdateLeaderboard(int longestGame, int achievementTotal, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = longestGame;
                _args[1] = achievementTotal;
                System.IAsyncResult _result = base.BeginInvoke("UpdateLeaderboard", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUpdateLeaderboard(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("UpdateLeaderboard", _args, result);
            }
            
            public System.IAsyncResult BeginGetLongestGame(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetLongestGame", _args, callback, asyncState);
                return _result;
            }
            
            public int EndGetLongestGame(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("GetLongestGame", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetHighestAchievementTotal(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetHighestAchievementTotal", _args, callback, asyncState);
                return _result;
            }
            
            public int EndGetHighestAchievementTotal(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("GetHighestAchievementTotal", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTopTenLongestGames(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTopTenLongestGames", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<int> EndGetTopTenLongestGames(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<int> _result = ((System.Collections.ObjectModel.ObservableCollection<int>)(base.EndInvoke("GetTopTenLongestGames", _args, result)));
                return _result;
            }
        }
    }
}
