class_name Enums

enum GameStates {
	STATENOCHANGE, STATELOADING, STATEEXIT,
	STATETITLE, STATEDECORATE, STATEOPTIONS, STATEGAME, STATEDEMO
}

# --- AI ENUMS ---

enum NAttrCrowd {
	ATTR_F_ACTION, ATTR_F_ENERGY, ATTR_F_CAN_START_WAVE
}

enum AttrCrowdActions {
	FA_MILLING, FA_CHEERING, FA_SLAMMING, FA_BOOING, FA_BLOCKING, FA_SHOUTING,
	FA_LOOK_UP, FA_LOOK_ULR, FA_LOOK_URL, FA_STAYIN_ALIVE, FA_WAVE, FA_PART
}

enum NAttrFrosh {
	ATTR_BEHAVIOR, ATTR_GOAL, ATTR_MOTIVATION, ATTR_STR, ATTR_FRAME,
	ATTR_PERSONALITY, ATTR_UPPER_LEVEL_GOAL, ATTR_MIND_SET, ATTR_PYRAMID_LEVEL,
	ATTR_HEIGHT_OF_FALL
}

enum SkinTones {
	SKIN_WHITE, SKIN_BROWN, SKIN_BLACK, SKIN_YELLOW, SKIN_PALE
}

enum MotivationLevels {
	MOTIVATION_LOW, MOTIVATION_SKEPTICAL, MOTIVATION_HIGH
}

enum MindSets {
	MINDSET_MOTIVATED, MINDSET_GULLIBLE, MINDSET_HUNGRY, MINDSET_THIRSTY, MINDSET_DRUNK
}

enum BAttrFrosh {
	ATTR_EXCITED, ATTR_LOOKING_LEFT, ATTR_LOOKING_AT_SCREEN, ATTR_WEIGHT_ON_SHOULDERS,
	ATTR_THIRSTY, ATTR_HUNGRY
}

enum NAttrFrecs {
	ATTR_EXCITEMENT
}

enum AttrArm {
	ATTR_ARM_STATUS, ATTR_ARM_ACTION, ATTR_UNKNOWN1, ATTR_UNKNOWN2, ATTR_UNKNOWN3, ATTR_KICKBACK
}

enum AttrProjectile {
	ATTR_START_X, ATTR_START_Y, ATTR_PROJECTILE_TYPE, ATTR_HIT_TARGET, ATTR_POWER_OF_THROW
}

enum ProjTypes {
	PROJ_APPLE, PROJ_GREASE, PROJ_CLARK, PROJ_PIZZA, PROJ_EXAM
}

enum BAttrMenuStartButtonAttributes {
	ATTR_MAKE_TITLE_SOUND_PLAY, ATTR_DO_NOT_ACTIVATE
}

enum NAttrExitAndCredits {
	ATTR_CREDITS_SCREEN
}

enum AttrAppleHitTargetConstants {
	ATTR_FLYING_TOWARD_TARGET, ATTR_FLYING_REBOUNDING, ATTR_FLYING_FLOATING_IN_PIT
}

enum AttrPrez {
	ATTR_PREZ_ACTION
}

enum AttrFlyInAndOut {
	ATTR_UNUSED1, ATTR_UNUSED2, ATTR_UNUSED3, ATTR_UNUSED4, ATTR_UNUSED5, ATTR_UNUSED6,
	ATTR_VELOCITY_X, ATTR_VELOCITY_Y
}

enum AttrBar {
	ATTR_BAR_GROUP, ATTR_ON_JACKET_POSITION, ATTR_ON_SCREEN_X, ATTR_ON_SCREEN_Y,
	ATTR_ASSOCIATED_SOUND, ATTR_ASSOCIATED_DISCIPLINE
}

enum BAttrBar {
	BATTR_BEING_DRAGGED
}

enum AttrToggleButton {
	ATTR_BUTTON_NUMBER, ATTR_ON_SCREEN_POSITION
}

enum AttrJacketSlam {
	ATTR_NEXT_STATE
}

enum NAttrForge {
	ATTR_FORGE_SWING, ATTR_FORGE_MOTION, ATTR_FORGE_ENERGY
}

enum AttrIcon {
	ATTR_ICON_STATUS, ATTR_POINTS_REQUIRED, ATTR_BUTTON_TYPE
}

enum AttrTam {
	ATTR_NAILS_IN_TAM, ATTR_TAM_STATUS
}

enum AttrForeGroundPopUpDudes {
	ATTR_RELATIVE_SPEED, ATTR_ENTRY_TYPE, ATTR_ON_SCREEN_TYPE, ATTR_EXIT_TYPE,
	ATTR_WEAPON_BEING_TAKEN
}

enum BAttrForeGroundPopUpDudes {
	ATTR_BEING_ATTACKED, ATTR_SCICON_BEHAVIOR, ATTR_MALE
}

enum Goals {
	GOAL_MINDLESS_WANDERING, GOAL_PYRAMID_SPOT, GOAL_CLIMBING_UP, GOAL_BOOSTING_UP,
	GOAL_BOOSTED_UP, GOAL_CLARK, GOAL_PIZZA, GOAL_ARTSCI, GOAL_COMMIE, GOAL_THINK, GOAL_MOSH
}

enum UpperLevelGoals {
	UPPER_GOAL_CLING, UPPER_GOAL_CLIMB, UPPER_GOAL_SUPPORT
}

enum Personalities {
	PERS_GOOFY, PERS_HEAVYWEIGHT, PERS_HOISTER, PERS_CLIMBER
}

enum ArmPositions {
	ARM_NOTHING, ARM_APPLE, ARM_PIZZA, ARM_CLARK, ARM_EXAM, ARM_GREASE,
	ARM_PUSH, ARM_IRON_RING, ARM_OTHROW, ARM_STHROW, ARM_STHROW2, ARM_STHROW3, ARM_CHANGING, ARM_DEMO
}

enum Buttons {
	BUTTON_TAUNT, BUTTON_APPLE, BUTTON_PIZZA, BUTTON_CLARK, BUTTON_EXAM,
	BUTTON_GREASE, BUTTON_RING
}

enum SpriteTextType {
    NONE, SMALL, LARGE
}

# --- END AI ENUMS ---

enum BitmapSets { bmpLoadBitmaps, bmpGameBitmaps, bmpMenuBitmaps, bmpTransBitmaps }

enum GreasepoleKeys {
	None,
	Back,
	IncreaseMunitions,
	ShowFPS,
	BuildRingEnergy,
	GWBalloon,
	PopupArtsciorCommie,
	PopupScicon,
	PopupHose,
	Mosh,
	StartDemo,
	ClarkC,
	ClarkH,
	ClarkP
}

# Full SpriteType enum from aiEnums.cs
enum SpriteType {
	# GAME
	SPRGAME_START,  # MARKER
	SPR_RIPPLE, SPR_CLOUDS, SPR_TREES, SPR_BACKDROP, SPR_PREZ, SPR_FORGE,
	SPR_PODIUM, SPR_POLE, SPR_FROSH, SPR_POWER_METER, SPR_WATER_METER, SPR_RING_METER, SPR_CONSOLE, SPR_GRID,
	SPR_MOUSE_CURSOR_TL, SPR_MOUSE_CURSOR_TR, SPR_MOUSE_CURSOR_BR, SPR_MOUSE_CURSOR_BL,
	SPR_APPLE_ICON, SPR_PIZZA_ICON, SPR_GREASE_ICON, SPR_CLARK_ICON,
	SPR_EXAM_ICON, SPR_RING_ICON, SPR_TAUNT_BUTTON, SPR_POINTS_ONES, SPR_WATER,
	SPR_APPLE_TENS, SPR_APPLE_ONES, SPR_PIZZA_TENS, SPR_PIZZA_ONES,
	SPR_CLARK_TENS, SPR_CLARK_ONES, SPR_EXAM_TENS, SPR_EXAM_ONES,
	SPR_ARM, SPR_ARM_RING_1, SPR_ARM_RING_2, SPR_ARM_RING_3, SPR_CLOSEUP_BEER,
	SPR_APPLE, SPR_GREASE, SPR_TAM, SPR_TRACKER_UL, SPR_TRACKER_LR, SPR_WHAP,
	SPR_EXAM, SPR_CLARK, SPR_PIZZA, SPR_SPLASH_S, SPR_SPLASH_M, SPR_SPLASH_ML, SPR_SPLASH_L, SPR_INANIMATE,
	SPR_FREC_GROUP, SPR_FREC_ACTION, SPR_SCICON_M, SPR_SCICON_F, SPR_UPPER_YEAR, SPR_POOF,
	SPR_GW_BALLOON, SPR_GW_HIPPO, SPR_HOSE_WHAP, SPR_GW_WORD_BUBBLE, SPR_HIGH_SCORE, SPR_POP_BOY_IN_CROWD, SPR_POP_BOY,
	SPR_PITTIME_HONES, SPR_PITTIME_HTENS, SPR_PITTIME_MONES, SPR_PITTIME_MTENS,
	SPR_PITTIME_SONES, SPR_PITTIME_STENS,
	SPR_POPUP_APPLES, SPR_POPUP_PIZZA, SPR_POPUP_BEER, SPR_POPUP_EXAM, SPR_POPUP_HOSE, SPR_POPUP_ARTSCIM,
	SPR_POPUP_ARTSCIF, SPR_POPUP_COMMIEM, SPR_POPUP_COMMIEF, SPR_POPUP_ENGINEER,
	SPR_ACHIEVEMENT_UNLOCKED, SPR_ACHIEVEMENT_UNLOCKED_TEXT1, SPR_ACHIEVEMENT_UNLOCKED_TEXT2,
	SPR_TRI, SPR_PUB, SPR_BAN,
	SPRGAME_END,  # MARKER

	# TRANS
	SPRTRANS_START,  # MARKER
	SPR_SLAM_JACKET,
	SPRTRANS_END,  # MARKER

	# MENU
	SPRMNU_START,  # MARKER
	SPRMNU_JACKET_BACK, SPRMNU_TITLEBACK, SPRMNU_OPTIONS_BACK, SPRMNU_OPTIONS_RETURN,
	SPRMNU_DECORATE_RETURN,
	SPRMNU_TITLEOPTIONS, SPRMNU_TITLESTART, SPRMNU_TITLEEXIT,
	SPRMNU_MOUSE_CURSOR,
	SPRMNU_BTN_TOGGLE0, SPRMNU_BTN_TOGGLE1, SPRMNU_BTN_TOGGLE2,
	SPRMNU_BTN_TOGGLE3, SPRMNU_BTN_TOGGLE4,
	SPRMNU_TXT_SELECT, SPRMNU_MENU_JACKET,
	SPRMNU_MENU_PASS_CREST,
	SPRMNU_BAR1, SPRMNU_BAR2, SPRMNU_BAR3, SPRMNU_BAR4, SPRMNU_BAR5, SPRMNU_BAR6,
	SPRMNU_BAR7, SPRMNU_BAR8, SPRMNU_BAR9, SPRMNU_BAR10, SPRMNU_BAR11,
	SPRMNU_BAR12, SPRMNU_BAR13, SPRMNU_BAR14, SPRMNU_BAR15,
	SPRMNU_BAR16, SPRMNU_BAR17, SPRMNU_BAR18, SPRMNU_BAR19,
	SPRMNU_BAR20, SPRMNU_AI_PREV_BAR_SCREEN, SPRMNU_AI_NEXT_BAR_SCREEN, SPRMNU_AI_NEXT_ACHIEVEMENT_SCREEN,
	SPRMNU_ACHIEVEMENT_TEXT, SPRMNU_ACHIEVEMENT_ADDITIONAL_TEXT,
	SPRMNU_END  # MARKER
}

# Layer names for coordinate conversion (must match Layers.gd initialization order)
enum LayerNames {
	LAYER_SKY,      # 0 - Upper-left corner of screen (clouds, balloon)
	LAYER_TREE,     # 1 - Base-of-trees-level
	LAYER_SKYLINE,  # 2 - Base-of-skyline-level (podium, prez)
	LAYER_FREC,     # 3 - Frecs level
	LAYER_PIT,      # 4 - Water level (pit, frosh, tossed items)
	LAYER_MISC      # 5 - Screen fixed (console, icons, mouse) - typ. 0 offset
}

enum GameBitmapEnumeration {
    # LOAD DIRECTORY
    bmpSPLASHSCREEN, bmpINVISIBLE, bmpBTNTOGGLE, bmpWHITE_DOT,
    bmpALP_COLON, bmpALP_PERIOD,
    bmpDIG_0, bmpDIG_1, bmpDIG_2, bmpDIG_3, bmpDIG_4, bmpDIG_5, bmpDIG_6, bmpDIG_7, bmpDIG_8, bmpDIG_9,
    bmpMOU_SELECT1, bmpMOU_SELECT2, bmpMOU_SELECT3,
    bmpMOU_TARBL, bmpMOU_TARBR, bmpMOU_TARTL, bmpMOU_TARTR,

    # GAME DIRECTORY (Frosh)
    bmpFR1_1, bmpFR1_2, bmpFR1_3, bmpFR1_4, bmpFR1_5, bmpFR1_6,
    bmpFR2_1, bmpFR2_2,
    bmpFR3_1, bmpFR3_2,
    bmpFR4A_1, bmpFR4A_2, bmpFR4A_3, bmpFR4A_4,
    bmpFR4B_1, bmpFR4B_2,
    bmpFR5A_1, bmpFR5A_2, bmpFR5A_3, bmpFR5A_4,
    bmpFR5B_1, bmpFR5B_2, bmpFR5B_3, bmpFR5B_4, bmpFR5B_5, bmpFR5B_6,
    bmpFR5C_1, bmpFR5C_2,
    bmpFR5D_1, bmpFR5D_2, bmpFR5D_3,
    bmpFR6A_1, bmpFR6A_2,
    bmpFR6B_1, bmpFR6B_2,
    bmpFR6C_1, bmpFR6C_2,
    bmpFR6D_1, bmpFR6D_2, bmpFR6D_3, bmpFR6D_4,
    bmpFR6E_1, bmpFR6E_2,
    bmpFR6F_1, bmpFR6F_2, bmpFR6F_3,

    bmpFR7A_1, bmpFR7A_2, bmpFR7A_3,
    bmpFR7B_1, bmpFR7B_2,
    bmpFR8_1, bmpFR8_2,
    bmpFR9A_1, bmpFR9A_2, bmpFR9A_3,
    bmpFR9B_1, bmpFR9B_2, bmpFR9B_3,
    bmpFR10_1, bmpFR10_2, bmpFR10_3,
    bmpFR11_1, bmpFR11_2, bmpFR11_3, bmpFR11_4, bmpFR11_5, bmpFR11_6, bmpFR11_7, bmpFR11_8, bmpFR11_9, bmpFR11_10,
    bmpFR11B_1, bmpFR11B_2, bmpFR11B_3,
    bmpFR14_1, bmpFR14_2, bmpFR14_3, bmpFR14_4,
    bmpFR15_1, bmpFR15_2, bmpFR15_3,
    bmpFR16A_1,
    bmpFR16B_1, bmpFR16B_2, bmpFR16B_3,
    bmpFR16C_1, bmpFR16C_2,
    bmpFR16D_1, bmpFR16D_2, bmpFR16D_3, bmpFR16D_4,
    bmpFR16E_1, bmpFR16E_2,
    bmpFR16F_1, bmpFR16F_2,
    bmpPOOF1, bmpPOOF2, bmpPOOF3, bmpPOOF4,

    # Offerings
    bmpOFFERAPPLES, bmpOFFERPIZZA, bmpOFFERCLARK, bmpOFFEREXAM, bmpOFFERHOSE,

    # Arms/Hands
    bmpHAND0_1, bmpHAND0_2, bmpHAND0_3,
    bmpHAND1_1, bmpHAND1_2, bmpHAND1_3, bmpHAND1_4, bmpHAND1_5, bmpHAND1_6, bmpHAND1_7, bmpHAND1_8,
    bmpHAND2_1, bmpHAND2_2,
    bmpHAND3_1, bmpHAND3_2, bmpHAND3_3, bmpHAND3_4, bmpHAND3_5,
    bmpHAND4_1, bmpHAND4_2, bmpHAND4_3,
    bmpHAND5_1, bmpHAND5_2, bmpHAND5_3,
    bmpHAND7_1, bmpHAND7_2, bmpHAND7_3, bmpHAND7_4, bmpHAND7_5, bmpHAND7_6, bmpHAND7_7,
    bmpHAND9_1,
    bmpCLOSEUPBEER1, bmpCLOSEUPBEER2,

    # Apples/Pizza/Clark/Exam/Hose
    bmpAPPLE1_1, bmpAPPLE2_1, bmpAPPLE3_1, bmpAPPLE4_1,
    bmpAPPLE5_1, bmpAPPLE5_2, bmpAPPLE5_3, bmpAPPLE5_4,
    bmpAPPLE6_1, bmpAPPLE7_1,
    bmpWHAP_1, bmpGLINT_1, bmpGLINT_2,
    bmpPIZZA1_1, bmpPIZZA2_1, bmpPIZZA3_1,
    bmpPIZZA4_1, bmpPIZZA4_2, bmpPIZZA4_3, bmpPIZZA4_4, bmpPIZZA4_5, bmpPIZZA4_6, bmpPIZZA4_7, bmpPIZZA4_8,
    bmpPIZZA5_1, bmpPIZZA6_1, bmpPIZZA7_1,
    bmpCLARK1_1, bmpCLARK2_1, bmpCLARK3_1, bmpCLARK4_1,
    bmpCLARK5A_1, bmpCLARK5A_2, bmpCLARK5A_3, bmpCLARK5A_4,
    bmpCLARK5B_1, bmpCLARK6_1, bmpCLARK7_1,
    bmpEXAM1_1, bmpEXAM2_1, bmpEXAM3_1,
    bmpEXAM4_1, bmpEXAM4_2, bmpEXAM4_3, bmpEXAM4_4,
    bmpHOSEBALL1, bmpHOSEBALL2, bmpHOSEBALL3, bmpHOSEBALL4, bmpHOSEBALL5, bmpHOSEBALL6, bmpHOSEBALL7,
    bmpHSPLASH1_1, bmpHSPLASH1_2, bmpHSPLASH1_3, bmpHSPLASH1_4, bmpHSPLASH1_5,
    bmpHSPLASH2_1, bmpHSPLASH2_2, bmpHSPLASH2_3, bmpHSPLASH2_4, bmpHSPLASH2_5,
    bmpHSPLASH3_1, bmpHSPLASH3_2, bmpHSPLASH3_3, bmpHSPLASH3_4, bmpHSPLASH3_5,
    bmpSPRAY1, bmpSPRAY2,

    # Pit
    bmpPOLE,
    bmpTAM0_1, bmpTAM0_2,
    bmpTAM1_1, bmpTAM1_2,
    bmpTAM2_1, bmpTAM2_2,
    bmpWATER,
    bmpSPLASHS1, bmpSPLASHS2, bmpSPLASHS3,
    bmpSPLASHM1, bmpSPLASHM2, bmpSPLASHM3,
    bmpSPLASHL1, bmpSPLASHL2, bmpSPLASHL3,
    bmpRIPPLE1, bmpRIPPLE2, bmpRIPPLE3,
    bmpWAKE1, bmpWAKE2, bmpWAKE3,

    # Students
    bmpARTSCIF_FALL1, bmpARTSCIF_FALL2, bmpARTSCIF_FALL3, bmpARTSCIF_HIT1,
    bmpARTSCIF_POPUP1, bmpARTSCIF_POPUP2,
    bmpARTSCIF_WADE1, bmpARTSCIF_WADE2, bmpARTSCIF_WADE3, bmpARTSCIF_WADE4,
    bmpARTSCIM_FALL1, bmpARTSCIM_FALL2, bmpARTSCIM_FALL3, bmpARTSCIM_HIT1, bmpARTSCIM_HIT2,
    bmpARTSCIM_POPUP1, bmpARTSCIM_POPUP2, bmpARTSCIM_POPUP3, bmpARTSCIM_POPUP4, bmpARTSCIM_POPUP5,
    bmpARTSCIM_WADE1, bmpARTSCIM_WADE2, bmpARTSCIM_WADE3, bmpARTSCIM_WADE4,
    bmpCOMMIEF_FALL1, bmpCOMMIEF_FALL2, bmpCOMMIEF_FALL3, bmpCOMMIEF_HIT1, bmpCOMMIEF_HIT2,
    bmpCOMMIEF_POPUP1, bmpCOMMIEF_POPUP2, bmpCOMMIEF_POPUP3, bmpCOMMIEF_POPUP4, bmpCOMMIEF_POPUP5,
    bmpCOMMIEF_WADE1, bmpCOMMIEF_WADE2, bmpCOMMIEF_WADE3, bmpCOMMIEF_WADE4,
    bmpCOMMIEM_FALL1, bmpCOMMIEM_FALL2, bmpCOMMIEM_FALL3, bmpCOMMIEM_HIT1,
    bmpCOMMIEM_POPUP1, bmpCOMMIEM_POPUP2, bmpCOMMIEM_POPUP3, bmpCOMMIEM_POPUP4, bmpCOMMIEM_POPUP5,
    bmpCOMMIEM_WADE1, bmpCOMMIEM_WADE2, bmpCOMMIEM_WADE3,

    # Popboys (Upper years)
    bmpPOPBOY1_1, bmpPOPBOY1_2, bmpPOPBOY1_3,
    bmpPOPBOY2_1, bmpPOPBOY2_2, bmpPOPBOY2_3, bmpPOPBOY2_4,
    bmpPOPBOY3_1, bmpPOPBOY3_2, bmpPOPBOY3_3, bmpPOPBOY3_4,
    bmpPOPBOY4_1, bmpPOPBOY4_2,
    bmpPOPBOY5_1, bmpPOPBOY5_2,
    bmpPOPBOY6_1, bmpPOPBOY6_2,
    bmpPOPBOY7_1, bmpPOPBOY7_2, bmpPOPBOY7_3, bmpPOPBOY7_4,

    # Back
    bmpPODIUM,
    bmpPREZ1_1, bmpPREZ1_2, bmpPREZ1_3,
    bmpPREZ2_1, bmpPREZ2_2, bmpPREZ2_3,
    bmpPREZ3_1, bmpPREZ3_2,
    bmpPREZ4_1, bmpPREZ4_2,

    # Frecs Action
    bmpAF_AppleBlock,
    bmpAF_Boo1, bmpAF_Boo2, bmpAF_Boo3,
    bmpAF_JacketSlam1, bmpAF_JacketSlam2, bmpAF_JacketSlam3,
    bmpAF_LameFrosh1, bmpAF_LameFrosh2, bmpAF_LameFrosh3,
    bmpAF_LookULR1, bmpAF_LookULR2, bmpAF_LookULR3,
    bmpAF_LookUp1,
    bmpAF_Milling1, bmpAF_Milling2,
    bmpAF_Part1, bmpAF_Part2,
    bmpAF_Shout1, bmpAF_Shout2, bmpAF_Shout3,
    bmpAF_Slam1, bmpAF_Slam2, bmpAF_Slam3,
    bmpAF_StayinAlive1, bmpAF_StayinAlive2,
    bmpAF_Wave1, bmpAF_Wave2, bmpAF_Wave3,

    # Gold Frecs
    bmpGF_AppleBlock,
    bmpGF_Boo1, bmpGF_Boo2, bmpGF_Boo3,
    bmpGF_Cheer1, bmpGF_Cheer2, bmpGF_Cheer3, bmpGF_Cheer4,
    bmpGF_LookULR1, bmpGF_LookULR2, bmpGF_LookULR3,
    bmpGF_LookUp1,
    bmpGF_Milling1, bmpGF_Milling2, bmpGF_Milling3,
    bmpGF_Shout1, bmpGF_Shout2,
    bmpGF_Slam1, bmpGF_Slam2, bmpGF_Slam3,
    bmpGF_StayinAlive1, bmpGF_StayinAlive2,
    bmpGF_Wave1, bmpGF_Wave2, bmpGF_Wave3,

    # SciCons
    bmpSCICONM1, bmpSCICONM2, bmpSCICONM3,
    bmpSCICONF1, bmpSCICONF2,

    # Background
    bmpTREES, bmpBACKDROP,
    bmpCLOUDS,
    bmpGWBALLOONL, bmpGWBALLOONLBANG, bmpGWBALLOONR, bmpGWBALLOONRBANG,
    bmpHIPPO0_1, bmpHIPPO0_2,
    bmpHIPPO1_1, bmpHIPPO1_2, bmpHIPPO1_3,
    bmpHIPPO2_1, bmpHIPPO2_2, bmpHIPPO2_3,
    bmpHIPPO3_1, bmpHIPPO3_2, bmpHIPPO3_3,
    bmpHIPPO4_1, bmpHIPPO4_2,
    bmpHIPPOWORDS1, bmpHIPPOWORDS2, bmpHIPPOWORDS3, bmpHIPPOWORDS4, bmpHIPPOWORDS5, bmpHIPPOWORDS6,

    # Icons
    bmpICOBAR,
    bmpICOAPPLE1, bmpICOAPPLE2, bmpICOAPPLE3,
    bmpICOPIZZA1, bmpICOPIZZA2, bmpICOPIZZA3,
    bmpICOCLARK1, bmpICOCLARK2, bmpICOCLARK3,
    bmpICOEXAM1, bmpICOEXAM2, bmpICOEXAM3,
    bmpFORGE1_1, bmpFORGE1_2, bmpFORGE1_3, bmpFORGE1_4,
    bmpFORGE2_2, bmpFORGE2_3, bmpFORGE2_4, bmpFORGE2_5,
    bmpFORGE3_2, bmpFORGE3_3, bmpFORGE3_4, bmpFORGE3_5,
    bmpFORGE4_2, bmpFORGE4_3, bmpFORGE4_4, bmpFORGE4_5,
    bmpFORGEDOWN,
    bmpICORING1, bmpICORING2, bmpICORING3, bmpICORING4, bmpICORING5,
    bmpPOWERBAR, bmpRINGBAR, bmpWATERBAR,
    bmpCONSOLE,
    bmpGRID1, bmpGRID2, bmpGRID3,
    bmpTRI, bmpPUB, bmpBAN,

    # MENU
    bmpJACKETBACK, bmpOPTIONSBACK,
    bmpTITLEBACK,
    bmpTITLESTARTGLOW1, bmpTITLESTART, bmpTITLESTARTGLOW2, bmpTITLESTARTGLOW3,
    bmpTITLEOPTIONS, bmpTITLEOPTIONSGLOW1, bmpTITLEOPTIONSGLOW2, bmpTITLEOPTIONSGLOW3,
    bmpTITLEEXIT,
    bmpTITLECREDITS1, bmpTITLECREDITS2, bmpTITLECREDITS3, bmpTITLECREDITS4, bmpTITLECREDITS5, bmpTITLECREDITS6, bmpTITLECREDITS7,
    bmpACHIEVEMENTUNLOCKED, bmpACHIEVEMENTUNLOCKED2,
    bmpMENUJACKET,
    bmpBAR1, bmpBAR2, bmpBAR3, bmpBAR4, bmpBAR5, bmpBAR6, bmpBAR7, bmpBAR8, bmpBAR9, bmpBAR10,
    bmpBAR11, bmpBAR12, bmpBAR13, bmpBAR14, bmpBAR15, bmpBAR16, bmpBAR17, bmpBAR18, bmpBAR19, bmpBAR20,
    bmpMENUPREVBARSCREEN, bmpBTNRETURN, bmpTXTSELECT,
    bmpMENUPASSCREST1, bmpMENUPASSCREST2, bmpMENUPASSCREST3,

    # TRANSITION
    bmpSLAMJACKET1, bmpSLAMJACKET2, bmpSLAMJACKET3, bmpSLAMJACKET4,

    bmpENDOFBITMAPS
}


# === SOUNDBANK INFO CONSTANTS ===
# Sound panning
const PAN_LEFT: int = -100
const PAN_CENTER: int = 0
const PAN_RIGHT: int = 100

# Volume levels
const VOL_10: int = 100
const VOL_9: int = 98
const VOL_8: int = 96
const VOL_7: int = 94
const VOL_6: int = 92
const VOL_5: int = 90
const VOL_4: int = 88
const VOL_3: int = 86
const VOL_2: int = 84
const VOL_1: int = 82

const VOL_FULL: int = 100
const VOL_DEFAULT: int = 94
const VOL_CROWD_SHOUT: int = 92
const VOL_CROWD: int = 90
const VOL_MUSIC: int = 90
const VOL_HOLLAR: int = 100
const VOL_NORMAL: int = 94

# Short sound list counts
const NSND_CLARK_FINISH: int = 4
const NSND_EFFECTS_WHOOSH: int = 2
const NSND_TAUNTS: int = 9
const NSND_EFFECTS_SMACK: int = 2

# Long sound list counts
const NSND_FROSH_CLARK_FINISH: int = 2
const NSND_WHOOSH: int = 2
const NSND_WHAP: int = 2
const NSND_EXAM_TOSS: int = 2
const NSND_FRECS_PROGRESS: int = 4
const NSND_FRECS_REWARD: int = 6
const NSND_ARTSCI_MALE_TAUNT: int = 7
const NSND_ARTSCI_FEMALE_TAUNT: int = 6
const NSND_COMMIE_MALE_TAUNT: int = 2
const NSND_COMMIE_FEMALE_TAUNT: int = 3
const NSND_FRECS_ROAR: int = 2
const NSND_FRECS_CHEER: int = 1
const NSND_FRECS_HIT_APPLE: int = 3
const NSND_FRECS_HIT_EXAM: int = 1


# === ASLList - Long Sound List ===
enum ASLList {
	LSND_APPLES_OFFER1,
	LSND_APPLES_OFFER2,
	LSND_APPLES_OFFER3,
	LSND_APPLES_OFFER4,
	LSND_APPLES_OFFER5,
	LSND_APPLES_OFFER6,
	LSND_APPLES_OFFER7,
	LSND_APPLES_OFFER8,
	LSND_APPLES_OFFER9,
	LSND_APPLES_OFFER10,
	LSND_APPLES_OFFERR1,
	LSND_APPLES_OFFERR2,
	LSND_ARTSCI_FEMALE_HIT1,
	LSND_ARTSCI_FEMALE_HIT2,
	LSND_ARTSCI_FEMALE_HIT3,
	LSND_ARTSCI_FEMALE_HIT4,
	LSND_ARTSCI_FEMALE_HIT5,
	LSND_ARTSCI_FEMALE_PUSH1,
	LSND_ARTSCI_FEMALE_TAUNT1,
	LSND_ARTSCI_FEMALE_TAUNT2,
	LSND_ARTSCI_FEMALE_TAUNT3,
	LSND_ARTSCI_FEMALE_TAUNT4,
	LSND_ARTSCI_FEMALE_TAUNT5,
	LSND_ARTSCI_FEMALE_TAUNT6,
	LSND_ARTSCI_MALE_HIT1,
	LSND_ARTSCI_MALE_HIT2,
	LSND_ARTSCI_MALE_HIT3,
	LSND_ARTSCI_MALE_HIT4,
	LSND_ARTSCI_MALE_HIT5,
	LSND_ARTSCI_MALE_HITR1,
	LSND_ARTSCI_MALE_HITR2,
	LSND_ARTSCI_MALE_HITR3,
	LSND_ARTSCI_MALE_PUSH1,
	LSND_ARTSCI_MALE_PUSH2,
	LSND_ARTSCI_MALE_PUSH3,
	LSND_ARTSCI_MALE_PUSH4,
	LSND_ARTSCI_MALE_TAUNT1,
	LSND_ARTSCI_MALE_TAUNT2,
	LSND_ARTSCI_MALE_TAUNT3,
	LSND_ARTSCI_MALE_TAUNT4,
	LSND_ARTSCI_MALE_TAUNT5,
	LSND_ARTSCI_MALE_TAUNT6,
	LSND_ARTSCI_MALE_TAUNT7,
	LSND_ARTSCI_MALE_TAUNTR1,
	LSND_CLARK_OFFER1,
	LSND_CLARK_OFFER2,
	LSND_CLARK_OFFER3,
	LSND_CLARK_OFFER4,
	LSND_CLARK_OFFER5,
	LSND_CLARK_OFFER6,
	LSND_CLARK_OFFERR1,
	LSND_CLARK_OFFERR2,
	LSND_CLARK_OFFERR3,
	LSND_CLARK_OFFERR4,
	LSND_COMMIE_FEMALE_HIT1,
	LSND_COMMIE_FEMALE_HIT2,
	LSND_COMMIE_FEMALE_HIT3,
	LSND_COMMIE_FEMALE_HIT4,
	LSND_COMMIE_FEMALE_PUSH1,
	LSND_COMMIE_FEMALE_TAUNT1,
	LSND_COMMIE_FEMALE_TAUNT2,
	LSND_COMMIE_FEMALE_TAUNT3,
	LSND_COMMIE_FEMALE_TAUNT4,
	LSND_COMMIE_MALE_HIT1,
	LSND_COMMIE_MALE_HIT2,
	LSND_COMMIE_MALE_HIT3,
	LSND_COMMIE_MALE_HIT4,
	LSND_COMMIE_MALE_HIT5,
	LSND_COMMIE_MALE_HIT6,
	LSND_COMMIE_MALE_HIT7,
	LSND_COMMIE_MALE_PHONE1,
	LSND_COMMIE_MALE_PHONE2,
	LSND_COMMIE_MALE_PUSH1,
	LSND_COMMIE_MALE_PUSH2,
	LSND_COMMIE_MALE_PUSH3,
	LSND_COMMIE_MALE_PUSH4,
	LSND_COMMIE_MALE_TAUNT1,
	LSND_COMMIE_MALE_TAUNT2,
	LSND_COMMIE_MALE_TAUNTR1,
	LSND_COMMIE_MALE_TAUNTR2,
	LSND_COMMIE_MALE_TAUNTR3,
	LSND_DISCIPLINES_APPLE,
	LSND_DISCIPLINES_CHEM,
	LSND_DISCIPLINES_CIVIL,
	LSND_DISCIPLINES_DEFAULT,
	LSND_DISCIPLINES_ELEC,
	LSND_DISCIPLINES_ENGCHEM,
	LSND_DISCIPLINES_ENGPHYS,
	LSND_DISCIPLINES_GEO,
	LSND_DISCIPLINES_MECH,
	LSND_DISCIPLINES_METALS,
	LSND_DISCIPLINES_MINING,
	LSND_DISCIPLINES_RITUAL,
	LSND_EXAM_OFFER1,
	LSND_EXAM_OFFER2,
	LSND_EXAM_OFFER3,
	LSND_EXAM_OFFER4,
	LSND_EXAM_OFFER5,
	LSND_EXAM_TOSS1,
	LSND_FRECS_BOO1,
	LSND_FRECS_BOO2,
	LSND_FRECS_BOO3,
	LSND_FRECS_CHANT1,
	LSND_FRECS_CHANTR1,
	LSND_FRECS_CHANTR2,
	LSND_FRECS_CHEER1,
	LSND_FRECS_HITAPPLE1,
	LSND_FRECS_HITAPPLE2,
	LSND_FRECS_HITAPPLE3,
	LSND_FRECS_HITEXAM1,
	LSND_FRECS_HOWHIGHTHEPOLE,
	LSND_FRECS_PROGRESS1,
	LSND_FRECS_PROGRESS2,
	LSND_FRECS_PROGRESS3,
	LSND_FRECS_PROGRESS4,
	LSND_FRECS_PROGRESSR1,
	LSND_FRECS_REWARD1,
	LSND_FRECS_REWARD2,
	LSND_FRECS_REWARD3,
	LSND_FRECS_REWARD4,
	LSND_FRECS_REWARD5,
	LSND_FRECS_REWARD6,
	LSND_FRECS_REWARDR1,
	LSND_FRECS_SLAM,
	LSND_FRECS_STEPHTOP1,
	LSND_FRECS_STEPHTOP2,
	LSND_FROSH_APPLEHIT1,
	LSND_FROSH_APPLEHIT2,
	LSND_FROSH_CLARKFINISH1,
	LSND_FROSH_CLARKFINISH2,
	LSND_FROSH_CLARKFINISH3,
	LSND_FROSH_ALPRAISE1,
	LSND_FROSH_ALPRAISE2,
	LSND_FROSH_ATTOP1,
	LSND_FROSH_ATTOP2,
	LSND_FROSH_ATTOP3,
	LSND_FROSH_ATTOP4,
	LSND_FROSH_ATTOP5,
	LSND_FROSH_GOTTAM1,
	LSND_FROSH_GOTTAM2,
	LSND_FROSH_GOTTAM3,
	LSND_FROSH_SHEEP1,
	LSND_FROSH_SHEEP2,
	LSND_FROSH_COW1,
	LSND_FROSH_COW2,
	LSND_HOSE_OFFER1,
	LSND_HOSE_OFFER2,
	LSND_HOSE_OFFER3,
	LSND_HOSE_OFFERR1,
	LSND_HOSE_TAKE1,
	LSND_HOSE_TAKE2,
	LSND_MUSIC_SCOTLAND,
	LSND_MUSIC_TITLEINIT,
	LSND_NARRATOR_CONGRATS,
	LSND_NARRATOR_GRAPHICSWARN,
	LSND_NARRATOR_JACKETINIT,
	LSND_NARRATOR_OPTIONINIT,
	LSND_NARRATOR_RITUALWARN,
	LSND_NARRATOR_STARTDELAY2,
	LSND_NARRATOR_STARTDELAY1,
	LSND_PIZZA_OFFER1,
	LSND_PIZZA_OFFER2,
	LSND_PIZZA_OFFER3,
	LSND_PIZZA_OFFERR1,
	LSND_POPBOY_ADVICE1,
	LSND_POPBOY_ADVICE2,
	LSND_POPBOY_ADVICE3,
	LSND_POPBOY_ADVICE4,
	LSND_POPBOY_ADVICE5,
	LSND_POPBOY_ADVICE6,
	LSND_POPBOY_APPLE1,
	LSND_POPBOY_APPLER1,
	LSND_POPBOY_BEER1,
	LSND_POPBOY_BEERR2,
	LSND_POPBOY_BEERR3,
	LSND_POPBOY_CHEER1,
	LSND_POPBOY_CHEER2,
	LSND_POPBOY_EXAM1,
	LSND_POPBOY_EXAM2,
	LSND_POPBOY_EXAM3,
	LSND_POPBOY_GOTTAM1,
	LSND_POPBOY_GREETING1,
	LSND_POPBOY_GREETING2,
	LSND_POPBOY_HIPPO1,
	LSND_POPBOY_HIPPOR1,
	LSND_POPBOY_PIZZA1,
	LSND_POPBOY_PIZZA2,
	LSND_PREZ_HITAPPLE1,
	LSND_PREZ_HITAPPLE2,
	LSND_PREZ_HITAPPLE3,
	LSND_PREZ_HITAPPLE4,
	LSND_PREZ_HITAPPLER4,
	LSND_PREZ_HITAPPLE5,
	LSND_PREZ_HITCLARK1,
	LSND_PREZ_HITCLARK2,
	LSND_PREZ_HITCLARK3,
	LSND_PREZ_HITEXAM,
	LSND_PREZ_HITHOSE1,
	LSND_PREZ_HITHOSE2,
	LSND_PREZ_HITHOSER2,
	LSND_PREZ_HITHOSER3,
	LSND_PREZ_HITHOSER4,
	LSND_PREZ_HITPIZZA1,
	LSND_PREZ_HITPIZZA2,
	LSND_PREZ_HITPIZZAR2,
	LSND_PREZ_ENCOURAGE1,
	LSND_PREZ_ENCOURAGE2,
	LSND_PREZ_ENCOURAGE3,
	LSND_PREZ_ENCOURAGE4,
	LSND_PREZ_ENCOURAGE5,
	LSND_PREZ_POPBOY1_1,
	LSND_PREZ_POPBOY1_2,
	LSND_PREZ_POPBOY1_3,
	LSND_PREZ_POPBOY2_1,
	LSND_PREZ_POPBOY2_2,
	LSND_RING_SWING,
	LSND_RING_DING,
	LSND_RING_PRESS,
	LSND_RING_RISE,
	LSND_RING_ZAP1,
	LSND_RING_ZAP2,
	LSND_RING_ZAP3,
	LSND_SCICONF_HIT_APPLES,
	LSND_SCICONF_HIT_BEER,
	LSND_SCICONF_HIT_EXAM,
	LSND_SCICONF_HIT_MISC,
	LSND_SCICONF_HIT_PIZZA,
	LSND_SCICONF_POPUP1,
	LSND_SCICONF_POPUP2,
	LSND_SCICONF_POPUP3,
	LSND_SCICONF_POPUP4,
	LSND_SCICONM_HIT_APPLES,
	LSND_SCICONM_HIT_BEER,
	LSND_SCICONM_HIT_EXAM,
	LSND_SCICONM_HIT_MISC,
	LSND_SCICONM_HIT_PIZZA,
	LSND_SCICONM_POPUP1,
	LSND_SCICONM_POPUP2,
	LSND_SCICONM_POPUP3
}


# === ASSList - Short Sound List ===
enum ASSList {
	SSND_EFFECTS_ACHIEVEMENTUNLOCKED,
	SSND_EFFECTS_ACHIEVEMENTUNLOCKED2,
	SSND_EFFECTS_CROWDMURMUR,
	SSND_EFFECTS_CROWDROAR1,
	SSND_EFFECTS_CROWDROAR2,
	SSND_EFFECTS_BIGJACKETWHOOSH,
	SSND_EFFECTS_BIGJACKETSLAM,
	SSND_EFFECTS_CHUG,
	SSND_EFFECTS_CHUGLASTDROP,
	SSND_EFFECTS_ICONIN,
	SSND_EFFECTS_ICONOUT,
	SSND_EFFECTS_KABOOM,
	SSND_EFFECTS_PIZZAEAT,
	SSND_EFFECTS_PIZZAREADY,
	SSND_EFFECTS_POUR,
	SSND_EFFECTS_PUNCH,
	SSND_EFFECTS_PUSH1,
	SSND_EFFECTS_SMACK1,
	SSND_EFFECTS_SMACK2,
	SSND_EFFECTS_SNATCH1,
	SSND_EFFECTS_SPLATTER,
	SSND_EFFECTS_TOPPLE,
	SSND_EFFECTS_TOSSBEER,
	SSND_EFFECTS_TOSSPIZZA,
	SSND_EFFECTS_WHOOSH1,
	SSND_EFFECTS_WHOOSH2,
	SSND_MENU_DECORATEREPEAT,
	SSND_MENU_DROP,
	SSND_MENU_GAMEINIT,
	SSND_MENU_LOADREPEAT,
	SSND_MENU_PLACEBAR,
	SSND_MENU_SELECT,
	SSND_MENU_TITLEREPEAT,
	SSND_MENU_TOGGLE,
	SSND_WATER_DRIP,
	SSND_WATER_RIPPLE,
	SSND_WATER_SPLASHBIG,
	SSND_WATER_SPLASHMID,
	SSND_WATER_SPLASHSMALL,
	SSND_WATER_HOSE
}


# === ALIASES FOR COMPATIBILITY ===
# These provide alternate names for enums to match different naming conventions used in code

# CrowdActions is an alias for AttrCrowdActions
const CrowdActions = AttrCrowdActions

# GameStates aliases for underscore variants
const STATE_TITLE = GameStates.STATETITLE
const STATE_LOADING = GameStates.STATELOADING
const STATE_EXIT = GameStates.STATEEXIT
const STATE_DECORATE = GameStates.STATEDECORATE
const STATE_OPTIONS = GameStates.STATEOPTIONS
const STATE_GAME = GameStates.STATEGAME
const STATE_DEMO = GameStates.STATEDEMO

