//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 17 Apr   10 4:10:31 PM
namespace SilverLegend.Web
{
    
    /// <summary>
    /// There are no comments for GreasepoleEntities in the schema.
    /// </summary>
    public partial class GreasepoleEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new GreasepoleEntities object using the connection string found in the 'GreasepoleEntities' section of the application configuration file.
        /// </summary>
        public GreasepoleEntities() : 
                base("name=GreasepoleEntities", "GreasepoleEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GreasepoleEntities object.
        /// </summary>
        public GreasepoleEntities(string connectionString) : 
                base(connectionString, "GreasepoleEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GreasepoleEntities object.
        /// </summary>
        public GreasepoleEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "GreasepoleEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Notifications in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Notification> Notifications
        {
            get
            {
                if ((this._Notifications == null))
                {
                    this._Notifications = base.CreateQuery<Notification>("[Notifications]");
                }
                return this._Notifications;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Notification> _Notifications;
        /// <summary>
        /// There are no comments for Notifications in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToNotifications(Notification notification)
        {
            base.AddObject("Notifications", notification);
        }
    }
    /// <summary>
    /// There are no comments for GreasepoleModel.Notification in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GreasepoleModel", Name="Notification")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Notification : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Notification object.
        /// </summary>
        /// <param name="notificationTime">Initial value of NotificationTime.</param>
        /// <param name="iPAddress">Initial value of IPAddress.</param>
        /// <param name="longestGame">Initial value of LongestGame.</param>
        /// <param name="achievementTotal">Initial value of AchievementTotal.</param>
        /// <param name="id">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Notification CreateNotification(global::System.DateTime notificationTime, string iPAddress, int longestGame, int achievementTotal, int id)
        {
            Notification notification = new Notification();
            notification.NotificationTime = notificationTime;
            notification.IPAddress = iPAddress;
            notification.LongestGame = longestGame;
            notification.AchievementTotal = achievementTotal;
            notification.Id = id;
            return notification;
        }
        /// <summary>
        /// There are no comments for property NotificationTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime NotificationTime
        {
            get
            {
                return this._NotificationTime;
            }
            set
            {
                this.OnNotificationTimeChanging(value);
                this.ReportPropertyChanging("NotificationTime");
                this._NotificationTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NotificationTime");
                this.OnNotificationTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _NotificationTime;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNotificationTimeChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNotificationTimeChanged();
        /// <summary>
        /// There are no comments for property IPAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string IPAddress
        {
            get
            {
                return this._IPAddress;
            }
            set
            {
                this.OnIPAddressChanging(value);
                this.ReportPropertyChanging("IPAddress");
                this._IPAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IPAddress");
                this.OnIPAddressChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _IPAddress;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIPAddressChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIPAddressChanged();
        /// <summary>
        /// There are no comments for property LongestGame in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int LongestGame
        {
            get
            {
                return this._LongestGame;
            }
            set
            {
                this.OnLongestGameChanging(value);
                this.ReportPropertyChanging("LongestGame");
                this._LongestGame = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LongestGame");
                this.OnLongestGameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _LongestGame;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLongestGameChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLongestGameChanged();
        /// <summary>
        /// There are no comments for property AchievementTotal in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int AchievementTotal
        {
            get
            {
                return this._AchievementTotal;
            }
            set
            {
                this.OnAchievementTotalChanging(value);
                this.ReportPropertyChanging("AchievementTotal");
                this._AchievementTotal = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AchievementTotal");
                this.OnAchievementTotalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _AchievementTotal;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAchievementTotalChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAchievementTotalChanged();
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
    }
}
